export const FETCH_LISTS = 'FETCH_LISTS';
export const FETCH_SHARED_LISTS = 'FETCH_SHARED_LISTS';
export const FETCH_LISTS_SUCCESS = 'FETCH_LISTS_SUCCESS';
export const FETCH_SHARED_LISTS_SUCCESS = 'FETCH_SHARED_LISTS_SUCCESS';
export const LIST_POST_SUCCESS = 'LIST_POST_SUCCESS';
export const TRYING_LIST_POST = 'TRYING_LIST_POST';
export const LIST_DELETE_SUCCESS = 'LIST_DELETE_SUCCESS';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_HAS_LOGIN = 'USER_HAS_LOGIN';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS';
export const USER_RESET_ERRORS = 'USER_RESET_ERRORS';

export const FETCH_ITEMS = 'FETCH_ITEMS';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const DISMISS_ITEMS = 'DISMISS_ITEMS';
export const FETCH_SINGLE_LIST_SUCCESS = 'FETCH_SINGLE_LIST_SUCCESS';

export const NO_FAB = 'NO_FAB';
export const CHANGE_FAB = 'CHANGE_FAB';
export const SET_NAVIGATOR = 'SET_NAVIGATOR';
